#!/bin/bash

# *****************************************************
# Install the lightstrands desktop widget into the
# "Add or Manage Widgets" panel.

# Color styling.
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[1;32m'
COLOR_YELLOW='\e[1;33m'
COLOR_BLUE='\e[0;34m'
COLOR_NORMAL='\033[0m'


# Uninstall it before it can be re-installed.
./uninstall
UNINSTALLED=$?

if [[ "$UNINSTALLED" != "0" ]]; then
    echo -e "${COLOR_YELLOW}""   (Lightstrands requires" \
        "a successful uninstall"
    echo "before it can be installed.)"
    echo -e "${COLOR_NORMAL}"
    exit 1
fi

# Try to install the package.
kpackagetool6 -t Plasma/Applet -i inc.skyrmion.lightstrands \
    1>/dev/null 2>/dev/null
INSTALLED=$?

# Report results.
if [[ "$INSTALLED" == "0" ]]; then
    echo -e "${COLOR_GREEN}""Lightstrands installed."
    echo -e "${COLOR_NORMAL}"
    exit 0
fi

if [[ "$INSTALLED" == "4" ]]; then
    echo -e "${COLOR_RED}""Lightstrands is already installed."
    echo ""
    echo -e "${COLOR_YELLOW}""You must manually uninstall" \
        "it before re-installing."
    echo "   use: ./uninstall"
    echo -e "${COLOR_NORMAL}"
else
    echo -e "${COLOR_RED}""Lightstrands cannot be installed."
    echo "   (kpackagetool6 error: ""$INSTALLED "")."
    echo ""
    echo -e "${COLOR_YELLOW}""report bug to: "
    echo "   https://github.com/markcapella/lightstrands/issues/new"
    echo -e "${COLOR_NORMAL}"
fi
