#!/bin/bash

# *****************************************************
# Install the lightstrands desktop widget into the
# "Add or Manage Widgets" panel.

# Color styling.
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[1;32m'
COLOR_YELLOW='\e[1;33m'
COLOR_BLUE='\e[0;34m'
COLOR_NORMAL='\033[0m'

# Install targets.
LANGS_DIR="translate/locale"
LANGS_PREFIX="plasma_applet_inc.skyrmion.lightstrands"

ICONS_TARGET="/usr/share/icons/hicolor/48x48/apps/"
LANGS_TARGET="/usr/share/locale"


# *****************************************************
# Main proces.
#

# Try to install the package.
kpackagetool6 -t Plasma/Applet -i inc.skyrmion.lightstrands \
    1>/dev/null 2>/dev/null
INSTALLED=$?
if [[ "$INSTALLED" == "0" ]]; then
    ./restartShell
    echo
    echo -e "${COLOR_GREEN}""Lightstrands installed." \
        "${COLOR_NORMAL}"
    exit 0
fi

# Else, update the package.
kpackagetool6 -t Plasma/Applet -u inc.skyrmion.lightstrands \
    1>/dev/null 2>/dev/null
UPDATED=$?
if [[ "$UPDATED" == "0" ]]; then
    ./restartShell
    echo
    echo -e "${COLOR_GREEN}""Lightstrands updated." \
        "${COLOR_NORMAL}"
    exit 0
fi

# Else, error. This should be unreachable.
echo
echo -e "${COLOR_RED}""Lightstrands cannot be installed."
echo "   (kpackagetool6 error: ""$UPDATED "")."
echo
echo -e "${COLOR_YELLOW}""report bug to: "
echo -e "   https://github.com/markcapella/lightstrands/issues/new"\
    "${COLOR_NORMAL}"
