#!/bin/bash

# *****************************************************
# Restart the plasma-shell.

# Color styling.
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[1;32m'
COLOR_YELLOW='\e[1;33m'
COLOR_BLUE='\e[0;34m'
COLOR_NORMAL='\033[0m'


# Restart plasmashell.
kquitapp6 plasmashell 1>/dev/null
kstart plasmashell
