#!/bin/bash

# *****************************************************
# Run the lightstrands desktop widget in French
# in the emulator.

# Start the emulator in French.
LANGUAGE=fr plasmoidviewer -a  inc.skyrmion.lightstrands/
