#!/bin/bash

# *****************************************************
# Uninstall the lightstrands desktop widget from the
# "Add or Manage Widgets" panel.

# Color styling.
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[1;32m'
COLOR_YELLOW='\e[1;33m'
COLOR_BLUE='\e[0;34m'
COLOR_NORMAL='\033[0m'

# Uninstall targets.
ICONS_TARGET="/usr/share/icons/hicolor/48x48/apps/"

LANGS_DIR="translate/locale"
LANGS_PREFIX="plasma_applet_inc.skyrmion.lightstrands"
LANGS_TARGET="/usr/share/locale"


# *****************************************************
# Main proces.
#

# Fail if widget has active desktop instances running.
cat ~/.config/plasma-org.kde.plasma.desktop-appletsrc \
    | grep lightstrands 1>/dev/null 2>/dev/null
EXISTS_AS_DESKTOP_ITEM=$?
if [[ $EXISTS_AS_DESKTOP_ITEM == "0" ]]; then
    echo -e "${COLOR_RED}"
    echo "A Lightstrands widget is active on your desktop."
    echo -e "${COLOR_YELLOW}"
    echo "   You must remove it manually, before you can"
    echo "uninstall it from the Widget Panel."\
        "${COLOR_NORMAL}"
    exit 1
fi

# Uninstall the package.
kpackagetool6 -t Plasma/Applet -r inc.skyrmion.lightstrands \
    1>/dev/null 2>/dev/null

# Restart plasmashell.
echo
echo -e "${COLOR_GREEN}""Lightstrands now uninstalled."\
    "${COLOR_NORMAL}"

kquitapp6 plasmashell 1>/dev/null
kstart plasmashell

