#!/bin/bash

# *****************************************************
# Uninstall the lightstrands desktop widget from the
# "Add or Manage Widgets" panel.

# Color styling.
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[1;32m'
COLOR_YELLOW='\e[1;33m'
COLOR_BLUE='\e[0;34m'
COLOR_NORMAL='\033[0m'


# See if widget has active desktop instances running.
cat ~/.config/plasma-org.kde.plasma.desktop-appletsrc \
    | grep lightstrands 1>/dev/null 2>/dev/null
EXISTS_AS_DESKTOP_ITEM=$?

# Result 0 says it's there.
if [[ $EXISTS_AS_DESKTOP_ITEM == "0" ]]; then
    echo -e "${COLOR_RED}"
    echo "A Lightstrands widget is active on your desktop."
    echo -e "${COLOR_YELLOW}"
    echo "   You must remove it manually, before you can"
    echo "uninstall it from the Widget Panel."
    echo -e "${COLOR_NORMAL}"
    exit 1
fi

# Try to uninstall the package.
kpackagetool6 -t Plasma/Applet -r inc.skyrmion.lightstrands \
    1>/dev/null 2>/dev/null
UNINSTALLED=$?

# Report results.
if [[ "$UNINSTALLED" == "0" ]]; then
    # Uninstall app icon available to "Add Widget panel".
    sudo rm -f /usr/share/icons/hicolor/48x48/apps/lightstrands.png
    sudo rm -f /usr/share/icons/hicolor/48x48/apps/lightstrands-credits.png

    sudo rm -f /usr/share/locale/de/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
    sudo rm -f /usr/share/locale/es/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
    sudo rm -f /usr/share/locale/fr/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
    sudo rm -f /usr/share/locale/it/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
    sudo rm -f /usr/share/locale/ja/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
    sudo rm -f /usr/share/locale/nl/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
    sudo rm -f /usr/share/locale/pt/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
    sudo rm -f /usr/share/locale/ru/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo

    echo ""
    echo -e "${COLOR_YELLOW}""Stopping Plasmashell."
    kquitapp6 plasmashell 1>/dev/null
    echo -e "${COLOR_YELLOW}""Restarting Plasmashell."
    kstart plasmashell
    echo ""
    echo -e "${COLOR_GREEN}""Lightstrands now uninstalled."
    echo -e "${COLOR_NORMAL}"
    exit 0
fi

echo ""
echo -e "${COLOR_YELLOW}""Lightstrands didn't require uninstall."
echo -e "${COLOR_NORMAL}"
