#!/bin/bash

# ************************************************
# This method converts all .XPM files
# in a working folder to .PNG format.
#

# Color styling.
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[1;32m'
COLOR_YELLOW='\e[1;33m'
COLOR_BLUE='\e[0;34m'
COLOR_NORMAL='\033[0m'


for f in $(ls *.xpm); do echo $f && convert $f "${f%.*}".png; done
