#!/bin/bash

# *****************************************************
# Extract all i18n() strings from source .js & .qml
# files into template.pot.

# Color styling.
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[1;32m'
COLOR_YELLOW='\e[1;33m'
COLOR_BLUE='\e[0;34m'
COLOR_NORMAL='\033[0m'


xgettext -L JavaScript -o template.pot --keyword=i18n \
    `find ../inc.skyrmion.lightstrands/contents -name '*.js' -o -name '*.qml'`
