#!/bin/bash

# *****************************************************
# At this point I'm manually changing all files in
# folder with text |charset=UTF-8| ---> |charset=UTF-8|

# Color styling.
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[1;32m'
COLOR_YELLOW='\e[1;33m'
COLOR_BLUE='\e[0;34m'
COLOR_NORMAL='\033[0m'


# Or else ./5fmtText will fail.
echo
echo -e "${COLOR_YELLOW}""   At this point I'm manually changing all files in"
echo -e "${COLOR_YELLOW}""folder with text charset = |ASCII| ---> |UTF-8|."
echo -e "${COLOR_NORMAL}"
