#!/bin/bash

# *****************************************************
# This method formats each base translated language
# .po file into runtime .mo files.

# Color styling.
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[1;32m'
COLOR_YELLOW='\e[1;33m'
COLOR_BLUE='\e[0;34m'
COLOR_NORMAL='\033[0m'


msgfmt -v deTranslated.po -o de.mo
msgfmt -v esTranslated.po -o es.mo
msgfmt -v frTranslated.po -o fr.mo
msgfmt -v itTranslated.po -o it.mo
msgfmt -v jaTranslated.po -o ja.mo
msgfmt -v nlTranslated.po -o nl.mo
msgfmt -v ptTranslated.po -o pt.mo
msgfmt -v ruTranslated.po -o ru.mo
