#!/bin/bash

# *****************************************************
# This method formats each base translated language
# .po file into runtime .mo files.

# Color styling.
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[1;32m'
COLOR_YELLOW='\e[1;33m'
COLOR_BLUE='\e[0;34m'
COLOR_NORMAL='\033[0m'


LANGS_TARGET="../inc.skyrmion.lightstrands/contents/locale/"

msgfmt -v deTranslated.po -o \
    "$LANGS_TARGET"/de/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
msgfmt -v esTranslated.po -o \
    "$LANGS_TARGET"/es/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
msgfmt -v frTranslated.po -o \
    "$LANGS_TARGET"/fr/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
msgfmt -v itTranslated.po -o \
    "$LANGS_TARGET"/it/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
msgfmt -v jaTranslated.po -o \
    "$LANGS_TARGET"/ja/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
msgfmt -v nlTranslated.po -o \
    "$LANGS_TARGET"/nl/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
msgfmt -v ptTranslated.po -o \
    "$LANGS_TARGET"/pt/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
msgfmt -v ruTranslated.po -o \
    "$LANGS_TARGET"/ru/LC_MESSAGES/plasma_applet_inc.skyrmion.lightstrands.mo
